# Generated by Django 5.2.3 on 2025-06-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('grado_estudios', models.CharField(choices=[('5p', '5to de primaria'), ('6p', '6to de primaria'), ('1s', '1ro de secundaria'), ('2s', '2do de secundaria'), ('3s', '3ro de secundaria'), ('4s', '4to de secundaria'), ('5s', '5to de secundaria'), ('pre', 'Preuniversitario')], max_length=30)),
                ('nombres_completos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('celular_llamadas', models.CharField(max_length=15)),
                ('numero_whatsapp', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('colegio_de_procedencia', models.CharField(max_length=100)),
                ('carrera_tentativa', models.CharField(max_length=100)),
                ('foto_previa', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_previas/')),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_frente/')),
                ('foto_corte', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_corte/')),
                ('sexo_data', models.CharField(choices=[('hija', 'hija'), ('hijo', 'hijo')], max_length=10)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del ciclo')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('parentesco', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Tio', 'Tío'), ('Tia', 'Tía'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='matriculas.alumno')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuotas', models.IntegerField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('congelada', 'Congelada'), ('retirada', 'Retirada'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='matriculas.alumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.apoderado')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.ciclo')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.horario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_registradas', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.turno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='matriculas.turno', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='turnos',
            field=models.ManyToManyField(related_name='ciclos', to='matriculas.turno', verbose_name='Turnos disponibles'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('turno', 'hora_inicio', 'hora_fin')},
        ),
    ]
