# Generated by Django 5.2.5 on 2025-08-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('grado_estudios', models.CharField(choices=[('5p', '5to de primaria'), ('6p', '6to de primaria'), ('1s', '1ro de secundaria'), ('2s', '2do de secundaria'), ('3s', '3ro de secundaria'), ('4s', '4to de secundaria'), ('5s', '5to de secundaria'), ('pre', 'Preuniversitario')], max_length=30)),
                ('nombres_completos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('celular_llamadas', models.CharField(max_length=9)),
                ('numero_whatsapp', models.CharField(max_length=9)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('colegio_de_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('carrera_tentativa', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_previa', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_previas/')),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_frente/')),
                ('foto_corte', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_corte/')),
                ('sexo_data', models.CharField(blank=True, choices=[('hija', 'hija'), ('hijo', 'hijo')], max_length=10)),
                ('direccion_alumno', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del ciclo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('activo', models.BooleanField(default=True, verbose_name='Ciclo activo')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Recordatorio de pago', max_length=50)),
                ('template', models.TextField(default='Estimado/a {apoderado}, le recordamos que tiene una cuota pendiente para la matrícula de {alumno} (cuota {numero_cuota}) por S/ {monto} con vencimiento el {fecha_vencimiento}. Por favor, regularice su pago para evitar inconvenientes.')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('celular', models.CharField(max_length=9)),
                ('direccion', models.TextField(blank=True, max_length=150, null=True)),
                ('parentesco', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Tio', 'Tío'), ('Tia', 'Tía'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumnos', models.ManyToManyField(related_name='apoderados', to='matriculas.alumno')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alumno', models.CharField(choices=[('pre_uni_promo', 'Ciclo Pre Universitario Promoción'), ('pre_uni_excelencia', 'Ciclo Pre Universitario Excelencia'), ('pre_uni_provincia', 'Ciclo Pre Universitario Provincia'), ('pre_uni_virtual', 'Ciclo Pre Universitario Virtual'), ('3_4_5_preferente', 'Ciclo 3ro, 4to y 5to Preferente'), ('1_2_3_basico', 'Ciclo 1ro, 2do y 3ro Básico'), ('cepunc_manana', 'CEPUNC Mañana')], default='pre_uni_promo', max_length=20)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuotas', models.IntegerField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('congelada', 'Congelada'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('tipo_matricula', models.CharField(choices=[('regular', 'REGULAR'), ('promocion', 'PROMOCION'), ('beca50', 'BECA 50%'), ('beca100', 'BECA 100%'), ('fondo_social', 'FONDO SOCIAL')], default='regular', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='matriculas.alumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.apoderado')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.ciclo')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.horario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_registradas', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.turno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='turnos',
            field=models.ManyToManyField(related_name='ciclos', to='matriculas.turno', verbose_name='Turnos disponibles'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Yape', 'Yape'), ('Transferencia', 'Transferencia bancaria'), ('Plin', 'Plin')], default='Efectivo', max_length=20)),
                ('numero_cuota', models.IntegerField(blank=True, null=True)),
                ('tipo_pago', models.CharField(choices=[('cuota', 'Cuota mensual'), ('matricula', 'Matrícula'), ('otros', 'Otros')], max_length=20)),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('observado', 'Observado')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='matriculas.matricula')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('matricula', 'numero_cuota', 'tipo_pago')},
            },
        ),
    ]
