# Generated by Django 5.2.3 on 2025-07-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='matriculas.apoderado'),
            preserve_default=False,
        ),
    ]
