# Generated by Django 5.2.5 on 2025-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dias_clase',
            field=models.CharField(blank=True, choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], help_text='Selecciona los días en que se dicta clase', max_length=7, null=True, verbose_name='Días de clase'),
        ),
    ]
