# Generated by Django 5.2.3 on 2025-07-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_remove_apoderado_alumno_alumno_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apoderado',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='alumno',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='matriculas.alumno'),
            preserve_default=False,
        ),
    ]
