# Generated by Django 5.2.5 on 2025-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_horario_dias_clase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['hora_inicio1'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dias_clase',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='dias_bloque1',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=7, verbose_name='Días (Bloque 1)'),
        ),
        migrations.AddField(
            model_name='horario',
            name='dias_bloque2',
            field=models.CharField(blank=True, choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=7, null=True, verbose_name='Días (Bloque 2)'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_fin1',
            field=models.TimeField(blank=True, default='13:00:00', null=True, verbose_name='Hora de fin (Bloque 1)'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_fin2',
            field=models.TimeField(blank=True, default='19:30:00', null=True, verbose_name='Hora de fin (Bloque 2)'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio1',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Hora de inicio (Bloque 1)'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio2',
            field=models.TimeField(blank=True, default='15:30:00', null=True, verbose_name='Hora de inicio (Bloque 2)'),
        ),
        migrations.AddField(
            model_name='horario',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: Turno Mañana, Turno Tarde L-X-V', max_length=100, verbose_name='Nombre del horario'),
        ),
    ]
