# Generated by Django 5.2.5 on 2025-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_alter_horario_options_remove_horario_dias_clase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
        migrations.AlterField(
            model_name='horario',
            name='dias_bloque1',
            field=models.CharField(help_text='Selecciona uno o más días, separados por coma', max_length=20, verbose_name='Días (Bloque 1)'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dias_bloque2',
            field=models.CharField(blank=True, help_text='Selecciona uno o más días, separados por coma', max_length=20, null=True, verbose_name='Días (Bloque 2)'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: Turno Mañana, Grupo Intensivo', max_length=100, verbose_name='Nombre del horario'),
        ),
    ]
