# Generated by Django 5.2.3 on 2025-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_remove_alumno_apoderado_apoderado_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='alumno',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='alumnos',
            field=models.ManyToManyField(related_name='apoderados', to='matriculas.alumno'),
        ),
    ]
