# Generated by Django 5.2.5 on 2025-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_alter_horario_options_alter_horario_dias_bloque1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dias_bloque1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dias_bloque2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
