# Generated by Django 5.1.4 on 2025-07-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_remove_apoderado_alumno_apoderado_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='tipo_alumno',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('promocion', 'PROMOCION'), ('beca50', 'BECA 50%'), ('beca100', 'BECA 100%'), ('fondo_social', 'FONDO SOCIAL')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='celular_llamadas',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_whatsapp',
            field=models.CharField(max_length=9),
        ),
    ]
