# Generated by Django 5.2.4 on 2025-07-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_matricula_tipo_alumno_alter_alumno_celular_llamadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='turnos',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Ciclo activo'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fecha_fin',
            field=models.DateField(default='2025-12-12', verbose_name='Fecha de finalización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fecha_inicio',
            field=models.DateField(default='2025-08-18', verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='celular',
            field=models.CharField(max_length=9),
        ),
    ]
