# Generated by Django 5.2.5 on 2025-08-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_alter_horario_dias_bloque1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='tipo_alumno',
            field=models.CharField(choices=[('pre_uni_promo', 'Ciclo Pre Universitario Promoción'), ('pre_uni_excelencia', 'Ciclo Pre Universitario Excelencia'), ('pre_uni_provincia', 'Ciclo Pre Universitario Provincia'), ('pre_uni_virtual', 'Ciclo Pre Universitario Virtual'), ('3_4_5_preferente', 'Ciclo 3ro, 4to y 5to Preferente'), ('1_2_3_basico', 'Ciclo 1ro, 2do y 3ro Básico'), ('cepunc_manana', 'CEPUNC Mañana'), ('cepunc_tarde', 'CEPUNC Tarde')], default='pre_uni_promo', max_length=20),
        ),
    ]
