# Generated by Django 5.2.4 on 2025-07-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_remove_ciclo_turnos_ciclo_activo_ciclo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='turnos',
            field=models.ManyToManyField(related_name='ciclos', to='matriculas.turno', verbose_name='Turnos disponibles'),
        ),
    ]
