# Generated by Django 5.2.4 on 2025-07-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_ciclo_turnos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('congelada', 'Congelada'), ('finalizada', 'Finalizada')], default='activa', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(blank=True, null=True)),
                ('tipo_pago', models.CharField(choices=[('cuota', 'Cuota mensual'), ('matricula', 'Matrícula'), ('otros', 'Otros')], max_length=20)),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('observado', 'Observado')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='matriculas.matricula')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('matricula', 'numero_cuota', 'tipo_pago')},
            },
        ),
    ]
