# Generated by Django 5.2.4 on 2025-07-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Recordatorio de pago', max_length=50)),
                ('template', models.TextField(default='Estimado/a {apoderado}, le recordamos que tiene una cuota pendiente para la matrícula de {alumno} (cuota {numero_cuota}) por S/ {monto} con vencimiento el {fecha_vencimiento}. Por favor, regularice su pago para evitar inconvenientes.')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
