# Generated by Django 5.2.4 on 2025-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_mensajewhatsappconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera_tentativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='colegio_de_procedencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo_data',
            field=models.CharField(blank=True, choices=[('hija', 'hija'), ('hijo', 'hijo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='direccion',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
