# Generated by Django 5.2.4 on 2025-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_alter_alumno_carrera_tentativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20),
        ),
    ]
