# Generated by Django 5.2.4 on 2025-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0012_alter_matricula_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('transferencia', 'Transferencia bancaria'), ('plin', 'Plin')], default='efectivo', max_length=20),
        ),
    ]
