# Generated by Django 5.2.4 on 2025-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0013_pago_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='tipo_ciclo',
            field=models.CharField(choices=[('pre_uni_promo', 'Ciclo Pre Universitario Promoción'), ('pre_uni_excelencia', 'Ciclo Pre Universitario Excelencia'), ('pre_uni_provincia', 'Ciclo Pre Universitario Provincia'), ('pre_uni_virtual', 'Ciclo Pre Universitario Virtual'), ('3_4_5_preferente', 'Ciclo 3ro, 4to y 5to Preferente'), ('1_2_3_basico', 'Ciclo 1ro, 2do y 3ro Básico'), ('cepunc_manana', 'CEPUNC Mañana')], default='pre_uni_promo', max_length=20),
        ),
    ]
