# Generated by Django 5.2.4 on 2025-08-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0014_matricula_tipo_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
