# Generated by Django 5.2.4 on 2025-08-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0015_alter_alumno_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion_alumno',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Yape', 'Yape'), ('Transferencia', 'Transferencia bancaria'), ('Plin', 'Plin')], default='Efectivo', max_length=20),
        ),
    ]
