# Generated by Django 5.2.4 on 2025-08-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0016_alumno_direccion_alumno_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='tipo_ciclo',
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipo_matricula',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('promocion', 'PROMOCION'), ('beca50', 'BECA 50%'), ('beca100', 'BECA 100%'), ('fondo_social', 'FONDO SOCIAL')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_alumno',
            field=models.CharField(choices=[('pre_uni_promo', 'Ciclo Pre Universitario Promoción'), ('pre_uni_excelencia', 'Ciclo Pre Universitario Excelencia'), ('pre_uni_provincia', 'Ciclo Pre Universitario Provincia'), ('pre_uni_virtual', 'Ciclo Pre Universitario Virtual'), ('3_4_5_preferente', 'Ciclo 3ro, 4to y 5to Preferente'), ('1_2_3_basico', 'Ciclo 1ro, 2do y 3ro Básico'), ('cepunc_manana', 'CEPUNC Mañana')], default='pre_uni_promo', max_length=20),
        ),
    ]
